name: Run Gradle on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 16
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Set executable permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app.jar
        path: ./build/libs/my-app.jar
